rocky8-deploy:
  extends: .deploy
  script:
    - ./deploy_packages.sh rockylinux
  needs:
    - rocky8-package
    - rocky8-test

rocky9-deploy:
  extends: .deploy
  script:
    - ./deploy_packages.sh rockylinux
  needs:
    - rocky9-package
    - rocky9-test

debian11-deploy:
  extends: .deploy
  script:
    - ./deploy_packages.sh debian bullseye
  needs:
    - debian11-package
    - debian11-test

debian12-deploy:
  extends: .deploy
  script:
    - ./deploy_packages.sh debian bookworm
  needs:
    - debian12-package
    - debian12-test

remi-rocky8-deploy:
  extends: .deploy
  script:
    - ./deploy_packages.sh rockylinux
  needs:
    - remi-rocky8-package
    - remi-rocky8-test

.deploy:
  stage: deploy
  tags: ["docker"]
  only:
    - master
    - /^release/.*$/

  before_script:
    - rm -f $CI_PROJECT_DIR/build/*devel*.rpm # Remove devel packages
    - cd $CI_PROJECT_DIR/build/ && for file in *; do mv "$file" $(echo "$file" | sed -e 's/[^A-Za-z0-9._+-]//g'); done || true && cd .. # Rename non standard packages
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_USER_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$DEPLOY_SERVER_HOST_KEY" >> ~/.ssh/known_hosts
    - |
      curl -o deploy_packages.sh --header "PRIVATE-TOKEN: ${TOOLS_REPOSITORY_TOKEN}" https://gitlab.linphone.org/api/v4/projects/368/repository/files/deploy_packages.sh/raw
    - chmod +x deploy_packages.sh

  after_script:
    - rm -rf ~/.ssh || true
    - rm -rf deploy_packages.sh || true
