rocky8-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky8-php:$ROCKY_8_IMAGE_VERSION
  script:
    - make rpm

debian11-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/debian11-php:$DEBIAN_11_IMAGE_VERSION
  script:
    - make deb

phpredis-remi-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky8-php:$ROCKY_8_IMAGE_VERSION
  script:
    - mkdir -p $CI_PROJECT_DIR/build
    - yum -y install wget php-devel gcc liblzf php-pear  php-pecl-igbinary-devel php-pecl-msgpack-devel lz4-devel liblzf-devel libzstd-devel
    - wget https://rpms.remirepo.net/SRPMS/$PHP_REDIS_REMI_VERSION.remi.src.rpm
    - rpmbuild --rebuild $PHP_REDIS_REMI_VERSION.remi.src.rpm
    - mv /root/rpmbuild/RPMS/*/*.rpm $CI_PROJECT_DIR/build
    - rm -r /root/rpmbuild

.package:
  tags: ["docker"]

  stage: package
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 1 day
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - flexiapi/vendor/
