rocky8-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky8-php:$ROCKY_8_IMAGE_VERSION
  script:
    # We install this dependency only for the pipeline
    - dnf -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    - dnf -y module reset php
    - dnf -y module enable php:remi-8.0
    - dnf -y update php\*
    - dnf -y install php-sodium
    - make rpm-el8

rocky9-package:
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky9-php:$ROCKY_9_IMAGE_VERSION
  script:
    - make rpm-el9

debian11-package:
  extends: .debian_package
  image: gitlab.linphone.org:4567/bc/public/docker/debian11-php:$DEBIAN_11_IMAGE_VERSION

debian12-package:
  extends: .debian_package
  image: gitlab.linphone.org:4567/bc/public/docker/debian12-php:$DEBIAN_12_IMAGE_VERSION

.debian_package:
  extends: .package
  script:
    - make deb

remi-rocky8-package:
  image: gitlab.linphone.org:4567/bc/public/docker/rocky8-php:$ROCKY_8_IMAGE_VERSION
  extends: .package
  script:
    - mkdir -p $CI_PROJECT_DIR/build
    - dnf -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    - yum -y install wget php-devel gcc liblzf php-pear lz4-devel liblzf-devel libzstd-devel php-pecl-apcu-devel
    # igbinary
    - wget https://rpms.remirepo.net/SRPMS/$PHP_IGBINARY_REMI_VERSION.remi.src.rpm
    - rpmbuild --rebuild $PHP_IGBINARY_REMI_VERSION.remi.src.rpm
    - rm /root/rpmbuild/RPMS/*/*debug*.rpm
    - mv /root/rpmbuild/RPMS/*/*devel*.rpm $CI_PROJECT_DIR/build/$PHP_IGBINARY_REMI_VERSION-devel.el8.x86_64.rpm || true # Rename to fit our naming format
    - mv /root/rpmbuild/RPMS/*/*.rpm $CI_PROJECT_DIR/build/$PHP_IGBINARY_REMI_VERSION.el8.x86_64.rpm # Rename to fit our naming format
    # msgpack
    - wget https://rpms.remirepo.net/SRPMS/$PHP_MSGPACK_REMI_VERSION.remi.src.rpm
    - rpmbuild --rebuild $PHP_MSGPACK_REMI_VERSION.remi.src.rpm
    - rm /root/rpmbuild/RPMS/*/*debug*.rpm
    - mv /root/rpmbuild/RPMS/*/*devel*.rpm $CI_PROJECT_DIR/build/$PHP_MSGPACK_REMI_VERSION-devel.el8.x86_64.rpm || true
    - mv /root/rpmbuild/RPMS/*/*.rpm $CI_PROJECT_DIR/build/$PHP_MSGPACK_REMI_VERSION.el8.x86_64.rpm
    # install and cleanup the dependencies
    - yum -y localinstall build/*.rpm
    - rm build/*.rpm
    # phpredis
    - wget https://rpms.remirepo.net/SRPMS/$PHP_REDIS_REMI_VERSION.remi.src.rpm
    - rpmbuild --rebuild $PHP_REDIS_REMI_VERSION.remi.src.rpm
    - rm /root/rpmbuild/RPMS/*/*debug*.rpm
    - mv /root/rpmbuild/RPMS/*/*devel*.rpm $CI_PROJECT_DIR/build/$PHP_REDIS_REMI_VERSION-devel.el8.x86_64.rpm || true
    - mv /root/rpmbuild/RPMS/*/*.rpm $CI_PROJECT_DIR/build/$PHP_REDIS_REMI_VERSION.el8.x86_64.rpm

    - rm -r /root/rpmbuild # Cleanup

.package:
  tags: ["docker"]

  stage: package
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 1 day
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - flexiapi/vendor/
