rocky8-package:
  needs:
    - prepare-package
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky8-php:$ROCKY_8_IMAGE_VERSION
  script:
    - make package-el8

rocky9-package:
  needs:
    - prepare-package
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky9-php:$ROCKY_9_IMAGE_VERSION
  script:
    - make package-el9

rocky10-package:
  needs:
    - prepare-package
  extends: .package
  image: gitlab.linphone.org:4567/bc/public/docker/rocky10-php:$ROCKY_10_IMAGE_VERSION
  script:
    - make package-el10

debian12-package:
  needs:
    - prepare-package
  extends: .debian_package
  image: gitlab.linphone.org:4567/bc/public/docker/debian12-php:$DEBIAN_12_IMAGE_VERSION

debian13-package:
  needs:
    - prepare-package
  extends: .debian_package
  image: gitlab.linphone.org:4567/bc/public/docker/debian13-php:$DEBIAN_13_IMAGE_VERSION

.debian_package:
  extends: .package
  script:
    - make package-deb

remi-rocky8-package:
  image: gitlab.linphone.org:4567/bc/public/docker/rocky8-php:$ROCKY_8_IMAGE_VERSION
  extends: .remi-rocky-package
  variables:
    ROCKY_RELEASE: 8
  before_script:
    - dnf -y module reset redis
    - dnf -y install @redis:6

.remi-rocky-package:
  extends: .package
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^release/ || $CI_COMMIT_REF_NAME == "master"
    #- changes:
    #  - .gitlab-ci.yml
  script:
    # Remi
    - mkdir -p $CI_PROJECT_DIR/build
    - dnf -y install https://rpms.remirepo.net/enterprise/remi-release-$ROCKY_RELEASE.rpm
    - yum -y install wget php-devel gcc liblzf php-pear lz4-devel liblzf-devel libzstd-devel php-pecl-apcu-devel
    # igbinary
    - wget https://rpms.remirepo.net/SRPMS/$PHP_IGBINARY_REMI_VERSION.remi.src.rpm
    - rpmbuild --rebuild $PHP_IGBINARY_REMI_VERSION.remi.src.rpm
    - rm /root/rpmbuild/RPMS/*/*debug*.rpm
    - mv /root/rpmbuild/RPMS/*/*devel*.rpm $CI_PROJECT_DIR/build/$PHP_IGBINARY_REMI_VERSION-devel.el$ROCKY_RELEASE.x86_64.rpm || true # Rename to fit our naming format
    - mv /root/rpmbuild/RPMS/*/*.rpm $CI_PROJECT_DIR/build/$PHP_IGBINARY_REMI_VERSION.el$ROCKY_RELEASE.x86_64.rpm # Rename to fit our naming format
    # msgpack
    - wget https://rpms.remirepo.net/SRPMS/$PHP_MSGPACK_REMI_VERSION.remi.src.rpm
    - rpmbuild --rebuild $PHP_MSGPACK_REMI_VERSION.remi.src.rpm
    - rm /root/rpmbuild/RPMS/*/*debug*.rpm
    - mv /root/rpmbuild/RPMS/*/*devel*.rpm $CI_PROJECT_DIR/build/$PHP_MSGPACK_REMI_VERSION-devel.el$ROCKY_RELEASE.x86_64.rpm || true
    - mv /root/rpmbuild/RPMS/*/*.rpm $CI_PROJECT_DIR/build/$PHP_MSGPACK_REMI_VERSION.el$ROCKY_RELEASE.x86_64.rpm
    # install and cleanup the dependencies
    - yum -y localinstall build/*.rpm
    # phpredis
    - wget https://rpms.remirepo.net/SRPMS/$PHP_REDIS_REMI_VERSION.remi.src.rpm
    - rpmbuild --rebuild $PHP_REDIS_REMI_VERSION.remi.src.rpm
    - rm /root/rpmbuild/RPMS/*/*debug*.rpm
    - mv /root/rpmbuild/RPMS/*/*devel*.rpm $CI_PROJECT_DIR/build/$PHP_REDIS_REMI_VERSION-devel.el$ROCKY_RELEASE.x86_64.rpm || true
    - mv /root/rpmbuild/RPMS/*/*.rpm $CI_PROJECT_DIR/build/$PHP_REDIS_REMI_VERSION.el$ROCKY_RELEASE.x86_64.rpm

    - rm -r /root/rpmbuild # Cleanup

.package:
  tags: ["docker"]

  stage: package
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 1 day

  variables:
    COMPOSER_CACHE_DIR: $CI_PROJECT_DIR/.composer/cache
    COMPOSER_ALLOW_SUPERUSER: 1

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - flexiapi/vendor/
      - .composer/cache
